name: Docker CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.201.190.104
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html

            echo "📥 Pull latest code"
            git pull origin main

            echo "🛑 Stop containers"
            docker compose down

            echo "🚀 Start containers"
            docker compose up -d
